### PR TITLE
Customers2

### PR DESCRIPTION
**Pull request by unusssualcode**
Full section DONE
Semantic code

### CODE REVIEW

**Review by andrew-sistuk — COMMENTED** [review]
https://www.loom.com/share/6537022071614c2babd67be7de077f5f?sid=ebc5d421-95c2-4e24-8e1c-1f3e4cd33994

**Comment by unusssualcode** [comment]
Виправив

**Review by andrew-sistuk — APPROVED** [review]
The best! Thanks!

**Comment by andrew-sistuk** [comment]
FULL customers section

**Pull request merged**
